name: test-server

on:
  pull_request:
    branches: [ main ]

jobs:
  test-server:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v2
    - run: npm ci
    - run: npm test